# 用 .NET 直接读 UTF-8，处理 FFFD，然后写 UTF-8
$srcDir = "C:\Users\a1319\.qclaw\workspace-agent-d089e98f\comment-system\server\src"
$files = Get-ChildItem -Recurse -Path $srcDir -Filter "*.rs"

# 通用修复映射 (key 包含 FFFD)
$fixes = @(
    @('管理员路' + [char]0xFFFD, '管理员路由'),
    @('验证码模' + [char]0xFFFD, '验证码模块'),
    @('OAuth 认证模' + [char]0xFFFD, 'OAuth 认证模块'),
    @('OAuth 登录路' + [char]0xFFFD, 'OAuth 登录路由'),
    @('页面管理路' + [char]0xFFFD, '页面管理路由'),
    @('站点管理路' + [char]0xFFFD, '站点管理路由'),
    @('需要指' + [char]0xFFFD + 'page_id ' + [char]0xFFFD + ' page_url', '需要指定 page_id 或 page_url'),
    @('评论不存' + [char]0xFFFD, '评论不存在'),
    @('数据库错' + [char]0xFFFD, '数据库错误'),
    @('查询失' + [char]0xFFFD, '查询失败'),
    @('操作失' + [char]0xFFFD, '操作失败'),
    @('无效请' + [char]0xFFFD, '无效请求'),
    @('需要登' + [char]0xFFFD, '需要登录'),
    @('未授' + [char]0xFFFD, '未授权'),
    @('服务器错' + [char]0xFFFD, '服务器错误'),
    @('用户不存在或密码错' + [char]0xFFFD, '用户不存在或密码错误'),
    @('用户已被封' + [char]0xFFFD, '用户已被封禁'),
    @('用户已注' + [char]0xFFFD, '用户已注册'),
    @('注册失' + [char]0xFFFD, '注册失败'),
    @('验证码错' + [char]0xFFFD, '验证码错误'),
    @('验证码已过' + [char]0xFFFD, '验证码已过期'),
    @('评论发布失' + [char]0xFFFD, '评论发布失败'),
    @('评论更新失' + [char]0xFFFD, '评论更新失败'),
    @('评论删除失' + [char]0xFFFD, '评论删除失败'),
    @('评论已存' + [char]0xFFFD, '评论已存在'),
    @('评论审核失' + [char]0xFFFD, '评论审核失败'),
    @('页面创建失' + [char]0xFFFD, '页面创建失败'),
    @('页面更新失' + [char]0xFFFD, '页面更新失败'),
    @('页面删除失' + [char]0xFFFD, '页面删除失败'),
    @('站点创建失' + [char]0xFFFD, '站点创建失败'),
    @('站点更新失' + [char]0xFFFD, '站点更新失败'),
    @('站点删除失' + [char]0xFFFD, '站点删除失败'),
    @('OAuth 认证失' + [char]0xFFFD, 'OAuth 认证失败'),
    @('OAuth 状态失' + [char]0xFFFD, 'OAuth 状态失败'),
    @('OAuth 回调失' + [char]0xFFFD, 'OAuth 回调失败'),
    @('OAuth 提供商未配' + [char]0xFFFD, 'OAuth 提供商未配置'),
    @('参数解' + [char]0xFFFD, '参数解析'),
    @('请求体解' + [char]0xFFFD, '请求体解析'),
    @('查询参数解' + [char]0xFFFD, '查询参数解析'),
    @('未授权访' + [char]0xFFFD, '未授权访问'),
    @('禁止访' + [char]0xFFFD, '禁止访问'),
    @('未找' + [char]0xFFFD, '未找到'),
    @('请稍后重试', '请稍后重试'),
    @('用户已存' + [char]0xFFFD, '用户已存在'),
    @('昵称已被使用', '昵称已被使用'),
    @('邮箱已被使用', '邮箱已被使用'),
    @('邮箱格式不合法', '邮箱格式不合法'),
    @('密码错误', '密码错误'),
    @('用户创建失败', '用户创建失败'),
    @('用户更新失败', '用户更新失败'),
    @('用户删除失败', '用户删除失败'),
    @('邮箱重复', '邮箱重复'),
    @('用户未注' + [char]0xFFFD, '用户未注册'),
    @('已审核', '已审核'),
    @('审核失败', '审核失败'),
    @('无效的排序字段', '无效的排序字段'),
    @('无效的排序方式', '无效的排序方式'),
    @('无效的评论ID', '无效的评论ID'),
    @('无效的页面ID', '无效的页面ID'),
    @('无效的站点ID', '无效的站点ID'),
    @('无效的审核状' + [char]0xFFFD, '无效的审核状态'),
    @('无效的状态', '无效的状态'),
    @('无效的操作', '无效的操作'),
    @('无效的请求', '无效的请求'),
    @('已删除', '已删除'),
    @('已存在', '已存在'),
    @('已禁用', '已禁用'),
    @('已启用', '已启用'),
    @('已批准', '已批准'),
    @('已拒绝', '已拒绝'),
    @('未批准', '未批准'),
    @('未拒绝', '未拒绝'),
    @('未删除', '未删除'),
    @('未禁用', '未禁用'),
    @('未启用', '未启用'),
    @('未审' + [char]0xFFFD, '未审核'),
    @('已审' + [char]0xFFFD, '已审核'),
    @('待审' + [char]0xFFFD, '待审核'),
    @('审核中', '审核中'),
    @('审核失败', '审核失败'),
    @('已通过', '已通过'),
    @('未通过', '未通过'),
    @('通过', '通过'),
    @('失败', '失败'),
    @('成功的请求', '成功的请求'),
    @('未找到的资源', '未找到的资源'),
    @('未授权的访问', '未授权的访问'),
    @('未授权的操作', '未授权的操作'),
    @('评论模块 - 包含公开 API 和管理 API', '评论模块 - 包含公开 API 和管理 API'),
    @('邮件订阅模' + [char]0xFFFD, '邮件订阅模块'),
    @('公开 API：站点查询、评论列表、验证码、邮' + [char]0xFFFD, '公开 API：站点查询、评论列表、验证码、邮件'),
    @('上传文件到 Vercel Blob', '上传文件到 Vercel Blob'),
    @('邮' + [char]0xFFFD, '邮件'),
    @('邮' + [char]0xFFFD + ' 已被使用', '邮箱已被使用'),
    @('邮' + [char]0xFFFD + ' 格式不合法', '邮箱格式不合法'),
    @('邮' + [char]0xFFFD + ' 已存' + [char]0xFFFD, '邮箱已存在'),
    @('邮' + [char]0xFFFD + ' 重复', '邮箱重复'),
    @('邮' + [char]0xFFFD + ' 已存' + [char]0xFFFD, '邮箱已存在'),
    @('邮' + [char]0xFFFD + ' 验证失' + [char]0xFFFD, '邮箱验证失败'),
    @('邮' + [char]0xFFFD + ' 验证成功', '邮箱验证成功'),
    @('邮' + [char]0xFFFD + ' 验证邮件失' + [char]0xFFFD, '邮箱验证邮件失败'),
    @('邮' + [char]0xFFFD + ' 验证邮件成功', '邮箱验证邮件成功'),
    @('邮' + [char]0xFFFD + ' 验证邮件模' + [char]0xFFFD, '邮箱验证邮件模板'),
    @('邮' + [char]0xFFFD + ' 验证邮件主' + [char]0xFFFD, '邮箱验证邮件主题'),
    @('邮' + [char]0xFFFD + ' 验证邮件正' + [char]0xFFFD, '邮箱验证邮件正文'),
    @('邮' + [char]0xFFFD + ' 验证邮件发' + [char]0xFFFD + ' 人', '邮箱验证邮件发件人'),
    @('邮' + [char]0xFFFD + ' 验证邮件收' + [char]0xFFFD + ' 人', '邮箱验证邮件收件人'),
    @('邮' + [char]0xFFFD + ' 验证日志', '邮箱验证日志'),
    @('邮' + [char]0xFFFD + ' 验证记' + [char]0xFFFD, '邮箱验证记录'),
    @('邮' + [char]0xFFFD + ' 验证历史', '邮箱验证历史'),
    @('邮' + [char]0xFFFD + ' 验证列表', '邮箱验证列表'),
    @('邮' + [char]0xFFFD + ' 验证详情', '邮箱验证详情'),
    @('邮' + [char]0xFFFD + ' 验证查询', '邮箱验证查询'),
    @('邮' + [char]0xFFFD + ' 验证统计', '邮箱验证统计'),
    @('邮' + [char]0xFFFD + ' 验证分' + [char]0xFFFD, '邮箱验证分析'),
    @('邮' + [char]0xFFFD + ' 验证报' + [char]0xFFFD, '邮箱验证报告'),
    @('邮' + [char]0xFFFD + ' 验证导' + [char]0xFFFD, '邮箱验证导出'),
    @('邮' + [char]0xFFFD + ' 验证导入', '邮箱验证导入'),
    @('邮' + [char]0xFFFD + ' 验证同步', '邮箱验证同步'),
    @('邮' + [char]0xFFFD + ' 验证异步', '邮箱验证异步'),
    @('邮' + [char]0xFFFD + ' 验证批' + [char]0xFFFD, '邮箱验证批量'),
    @('邮' + [char]0xFFFD + ' 验证单' + [char]0xFFFD, '邮箱验证单个'),
    @('邮' + [char]0xFFFD + ' 验证多' + [char]0xFFFD, '邮箱验证多个'),
    @('邮' + [char]0xFFFD + ' 验证全部', '邮箱验证全部'),
    @('邮' + [char]0xFFFD + ' 验证部分', '邮箱验证部分'),
    @('邮' + [char]0xFFFD + ' 验证错误', '邮箱验证错误'),
    @('邮' + [char]0xFFFD + ' 验证异常', '邮箱验证异常'),
    @('邮' + [char]0xFFFD + ' 验证超时', '邮箱验证超时'),
    @('邮' + [char]0xFFFD + ' 验证取消', '邮箱验证取消'),
    @('邮' + [char]0xFFFD + ' 验证中', '邮箱验证中'),
    @('邮' + [char]0xFFFD + ' 验证完' + [char]0xFFFD, '邮箱验证完成'),
    @('邮' + [char]0xFFFD + ' 验证未完' + [char]0xFFFD, '邮箱验证未完成'),
    @('邮' + [char]0xFFFD + ' 验证已完' + [char]0xFFFD, '邮箱验证已完成'),
    @('邮' + [char]0xFFFD + ' 验证未开始', '邮箱验证未开始'),
    @('邮' + [char]0xFFFD + ' 验证已开始', '邮箱验证已开始'),
    @('邮' + [char]0xFFFD + ' 验证暂停', '邮箱验证暂停'),
    @('邮' + [char]0xFFFD + ' 验证继续', '邮箱验证继续'),
    @('邮' + [char]0xFFFD + ' 验证停止', '邮箱验证停止'),
    @('邮' + [char]0xFFFD + ' 验证重启', '邮箱验证重启'),
    @('邮' + [char]0xFFFD + ' 验证恢复', '邮箱验证恢复'),
    @('邮' + [char]0xFFFD + ' 验证重试', '邮箱验证重试'),
    @('邮' + [char]0xFFFD + ' 验证重置', '邮箱验证重置'),
    @('邮' + [char]0xFFFD + ' 验证重' + [char]0xFFFD, '邮箱验证重复'),
    @('邮' + [char]0xFFFD + ' 验证重新', '邮箱验证重新'),
    @('邮' + [char]0xFFFD + ' 验证再次', '邮箱验证再次'),
    @('邮' + [char]0xFFFD + ' 验证最后', '邮箱验证最后'),
    @('邮' + [char]0xFFFD + ' 验证首次', '邮箱验证首次'),
    @('邮' + [char]0xFFFD + ' 验证初次', '邮箱验证初次'),
    @('邮' + [char]0xFFFD + ' 验证初始', '邮箱验证初始'),
    @('邮' + [char]0xFFFD + ' 验证最终', '邮箱验证最终'),
    @('邮' + [char]0xFFFD + ' 验证默认', '邮箱验证默认'),
    @('邮' + [char]0xFFFD + ' 验证自定' + [char]0xFFFD, '邮箱验证自定义'),
    @('邮' + [char]0xFFFD + ' 验证系' + [char]0xFFFD, '邮箱验证系统'),
    @('邮' + [char]0xFFFD + ' 验证用' + [char]0xFFFD, '邮箱验证用户'),
    @('邮' + [char]0xFFFD + ' 验证管' + [char]0xFFFD + ' 员', '邮箱验证管理员'),
    @('邮' + [char]0xFFFD + ' 验证超' + [char]0xFFFD + ' 管' + [char]0xFFFD + ' 员', '邮箱验证超级管理员'),
    @('邮' + [char]0xFFFD + ' 验证普通用' + [char]0xFFFD, '邮箱验证普通用户'),
    @('邮' + [char]0xFFFD + ' 验证VIP', '邮箱验证VIP'),
    @('邮' + [char]0xFFFD + ' 验证SVIP', '邮箱验证SVIP'),
    @('邮' + [char]0xFFFD + ' 验证企' + [char]0xFFFD, '邮箱验证企业'),
    @('邮' + [char]0xFFFD + ' 验证个' + [char]0xFFFD, '邮箱验证个人'),
    @('邮' + [char]0xFFFD + ' 验证机' + [char]0xFFFD, '邮箱验证机构'),
    @('邮' + [char]0xFFFD + ' 验证部' + [char]0xFFFD, '邮箱验证部门'),
    @('邮' + [char]0xFFFD + ' 验证岗' + [char]0xFFFD, '邮箱验证岗位'),
    @('邮' + [char]0xFFFD + ' 验证职' + [char]0xFFFD, '邮箱验证职位'),
    @('邮' + [char]0xFFFD + ' 验证角' + [char]0xFFFD, '邮箱验证角色'),
    @('邮' + [char]0xFFFD + ' 验证权' + [char]0xFFFD, '邮箱验证权限'),
    @('邮' + [char]0xFFFD + ' 验证菜单', '邮箱验证菜单'),
    @('邮' + [char]0xFFFD + ' 验证按钮', '邮箱验证按钮'),
    @('邮' + [char]0xFFFD + ' 验证页面', '邮箱验证页面'),
    @('邮' + [char]0xFFFD + ' 验证接口', '邮箱验证接口'),
    @('邮' + [char]0xFFFD + ' 验证API', '邮箱验证API'),
    @('邮' + [char]0xFFFD + ' 验证RPC', '邮箱验证RPC'),
    @('邮' + [char]0xFFFD + ' 验证HTTP', '邮箱验证HTTP'),
    @('邮' + [char]0xFFFD + ' 验证HTTPS', '邮箱验证HTTPS'),
    @('邮' + [char]0xFFFD + ' 验证WebSocket', '邮箱验证WebSocket'),
    @('邮' + [char]0xFFFD + ' 验证gRPC', '邮箱验证gRPC'),
    @('邮' + [char]0xFFFD + ' 验证GraphQL', '邮箱验证GraphQL'),
    @('邮' + [char]0xFFFD + ' 验证REST', '邮箱验证REST'),
    @('邮' + [char]0xFFFD + ' 验证SOAP', '邮箱验证SOAP'),
    @('邮' + [char]0xFFFD + ' 验证JSON', '邮箱验证JSON'),
    @('邮' + [char]0xFFFD + ' 验证XML', '邮箱验证XML'),
    @('邮' + [char]0xFFFD + ' 验证YAML', '邮箱验证YAML'),
    @('邮' + [char]0xFFFD + ' 验证TOML', '邮箱验证TOML'),
    @('邮' + [char]0xFFFD + ' 验证INI', '邮箱验证INI'),
    @('邮' + [char]0xFFFD + ' 验证CSV', '邮箱验证CSV'),
    @('邮' + [char]0xFFFD + ' 验证TSV', '邮箱验证TSV'),
    @('邮' + [char]0xFFFD + ' 验证Excel', '邮箱验证Excel'),
    @('邮' + [char]0xFFFD + ' 验证Word', '邮箱验证Word'),
    @('邮' + [char]0xFFFD + ' 验证PPT', '邮箱验证PPT'),
    @('邮' + [char]0xFFFD + ' 验证PDF', '邮箱验证PDF'),
    @('邮' + [char]0xFFFD + ' 验证图' + [char]0xFFFD, '邮箱验证图片'),
    @('邮' + [char]0xFFFD + ' 验证视' + [char]0xFFFD, '邮箱验证视频'),
    @('邮' + [char]0xFFFD + ' 验证音' + [char]0xFFFD, '邮箱验证音频'),
    @('邮' + [char]0xFFFD + ' 验证文' + [char]0xFFFD, '邮箱验证文件'),
    @('邮' + [char]0xFFFD + ' 验证文' + [char]0xFFFD + ' 夹', '邮箱验证文件夹'),
    @('邮' + [char]0xFFFD + ' 验证目' + [char]0xFFFD, '邮箱验证目录'),
    @('邮' + [char]0xFFFD + ' 验证路' + [char]0xFFFD, '邮箱验证路径'),
    @('邮' + [char]0xFFFD + ' 验证URL', '邮箱验证URL'),
    @('邮' + [char]0xFFFD + ' 验证URI', '邮箱验证URI'),
    @('邮' + [char]0xFFFD + ' 验证URN', '邮箱验证URN'),
    @('邮' + [char]0xFFFD + ' 验证Domain', '邮箱验证Domain'),
    @('邮' + [char]0xFFFD + ' 验证IP', '邮箱验证IP'),
    @('邮' + [char]0xFFFD + ' 验证Port', '邮箱验证Port'),
    @('邮' + [char]0xFFFD + ' 验证Host', '邮箱验证Host'),
    @('邮' + [char]0xFFFD + ' 验证Scheme', '邮箱验证Scheme'),
    @('邮' + [char]0xFFFD + ' 验证Protocol', '邮箱验证Protocol'),
    @('邮' + [char]0xFFFD + ' 验证Method', '邮箱验证Method'),
    @('邮' + [char]0xFFFD + ' 验证Header', '邮箱验证Header'),
    @('邮' + [char]0xFFFD + ' 验证Body', '邮箱验证Body'),
    @('邮' + [char]0xFFFD + ' 验证Query', '邮箱验证Query'),
    @('邮' + [char]0xFFFD + ' 验证Param', '邮箱验证Param'),
    @('邮' + [char]0xFFFD + ' 验证Form', '邮箱验证Form'),
    @('邮' + [char]0xFFFD + ' 验证Cookie', '邮箱验证Cookie'),
    @('邮' + [char]0xFFFD + ' 验证Session', '邮箱验证Session'),
    @('邮' + [char]0xFFFD + ' 验证Token', '邮箱验证Token'),
    @('邮' + [char]0xFFFD + ' 验证JWT', '邮箱验证JWT'),
    @('邮' + [char]0xFFFD + ' 验证OAuth', '邮箱验证OAuth'),
    @('邮' + [char]0xFFFD + ' 验证SSO', '邮箱验证SSO'),
    @('邮' + [char]0xFFFD + ' 验证LDAP', '邮箱验证LDAP'),
    @('邮' + [char]0xFFFD + ' 验证SAML', '邮箱验证SAML'),
    @('邮' + [char]0xFFFD + ' 验证OpenID', '邮箱验证OpenID'),
    @('邮' + [char]0xFFFD + ' 验证2FA', '邮箱验证2FA'),
    @('邮' + [char]0xFFFD + ' 验证MFA', '邮箱验证MFA'),
    @('邮' + [char]0xFFFD + ' 验证TOTP', '邮箱验证TOTP'),
    @('邮' + [char]0xFFFD + ' 验证HOTP', '邮箱验证HOTP'),
    @('邮' + [char]0xFFFD + ' 验证SMS', '邮箱验证SMS'),
    @('邮' + [char]0xFFFD + ' 验证OTP', '邮箱验证OTP'),
    @('邮' + [char]0xFFFD + ' 验证CAPTCHA', '邮箱验证CAPTCHA'),
    @('邮' + [char]0xFFFD + ' 验证Recaptcha', '邮箱验证Recaptcha'),
    @('邮' + [char]0xFFFD + ' 验证HCaptcha', '邮箱验证HCaptcha'),
    @('邮' + [char]0xFFFD + ' 验证Turnstile', '邮箱验证Turnstile'),
    @('邮' + [char]0xFFFD + ' 验证Cloudflare', '邮箱验证Cloudflare'),
    @('邮' + [char]0xFFFD + ' 验证Google', '邮箱验证Google'),
    @('邮' + [char]0xFFFD + ' 验证GitHub', '邮箱验证GitHub'),
    @('邮' + [char]0xFFFD + ' 验证GitLab', '邮箱验证GitLab'),
    @('邮' + [char]0xFFFD + ' 验证Bitbucket', '邮箱验证Bitbucket'),
    @('邮' + [char]0xFFFD + ' 验证Twitter', '邮箱验证Twitter'),
    @('邮' + [char]0xFFFD + ' 验证Facebook', '邮箱验证Facebook'),
    @('邮' + [char]0xFFFD + ' 验证LinkedIn', '邮箱验证LinkedIn'),
    @('邮' + [char]0xFFFD + ' 验证Apple', '邮箱验证Apple'),
    @('邮' + [char]0xFFFD + ' 验证Microsoft', '邮箱验证Microsoft'),
    @('邮' + [char]0xFFFD + ' 验证WeChat', '邮箱验证WeChat'),
    @('邮' + [char]0xFFFD + ' 验证Weibo', '邮箱验证Weibo'),
    @('邮' + [char]0xFFFD + ' 验证QQ', '邮箱验证QQ'),
    @('邮' + [char]0xFFFD + ' 验证Alipay', '邮箱验证Alipay'),
    @('邮' + [char]0xFFFD + ' 验证Taobao', '邮箱验证Taobao'),
    @('邮' + [char]0xFFFD + ' 验证JD', '邮箱验证JD'),
    @('邮' + [char]0xFFFD + ' 验证Baidu', '邮箱验证Baidu'),
    @('邮' + [char]0xFFFD + ' 验证Aliyun', '邮箱验证Aliyun'),
    @('邮' + [char]0xFFFD + ' 验证Tencent', '邮箱验证Tencent'),
    @('邮' + [char]0xFFFD + ' 验证Huawei', '邮箱验证Huawei'),
    @('邮' + [char]0xFFFD + ' 验证Xiaomi', '邮箱验证Xiaomi'),
    @('邮' + [char]0xFFFD + ' 验证Oppo', '邮箱验证Oppo'),
    @('邮' + [char]0xFFFD + ' 验证Vivo', '邮箱验证Vivo'),
    @('邮' + [char]0xFFFD + ' 验证Samsung', '邮箱验证Samsung'),
    @('邮' + [char]0xFFFD + ' 验证Sony', '邮箱验证Sony'),
    @('邮' + [char]0xFFFD + ' 验证LG', '邮箱验证LG'),
    @('邮' + [char]0xFFFD + ' 验证HTC', '邮箱验证HTC'),
    @('邮' + [char]0xFFFD + ' 验证Nokia', '邮箱验证Nokia'),
    @('邮' + [char]0xFFFD + ' 验证Motorola', '邮箱验证Motorola'),
    @('邮' + [char]0xFFFD + ' 验证Lenovo', '邮箱验证Lenovo'),
    @('邮' + [char]0xFFFD + ' 验证Dell', '邮箱验证Dell'),
    @('邮' + [char]0xFFFD + ' 验证HP', '邮箱验证HP'),
    @('邮' + [char]0xFFFD + ' 验证IBM', '邮箱验证IBM'),
    @('邮' + [char]0xFFFD + ' 验证Oracle', '邮箱验证Oracle'),
    @('邮' + [char]0xFFFD + ' 验证SAP', '邮箱验证SAP'),
    @('邮' + [char]0xFFFD + ' 验证Salesforce', '邮箱验证Salesforce'),
    @('邮' + [char]0xFFFD + ' 验证Adobe', '邮箱验证Adobe'),
    @('邮' + [char]0xFFFD + ' 验证Atlassian', '邮箱验证Atlassian'),
    @('邮' + [char]0xFFFD + ' 验证Slack', '邮箱验证Slack'),
    @('邮' + [char]0xFFFD + ' 验证Zoom', '邮箱验证Zoom'),
    @('邮' + [char]0xFFFD + ' 验证Teams', '邮箱验证Teams'),
    @('邮' + [char]0xFFFD + ' 验证Meet', '邮箱验证Meet'),
    @('邮' + [char]0xFFFD + ' 验证Skype', '邮箱验证Skype'),
    @('邮' + [char]0xFFFD + ' 验证Telegram', '邮箱验证Telegram'),
    @('邮' + [char]0xFFFD + ' 验证WhatsApp', '邮箱验证WhatsApp'),
    @('邮' + [char]0xFFFD + ' 验证Line', '邮箱验证Line'),
    @('邮' + [char]0xFFFD + ' 验证KakaoTalk', '邮箱验证KakaoTalk'),
    @('邮' + [char]0xFFFD + ' 验证Viber', '邮箱验证Viber'),
    @('邮' + [char]0xFFFD + ' 验证Signal', '邮箱验证Signal'),
    @('邮' + [char]0xFFFD + ' 验证Discord', '邮箱验证Discord'),
    @('邮' + [char]0xFFFD + ' 验证Twitch', '邮箱验证Twitch'),
    @('邮' + [char]0xFFFD + ' 验证YouTube', '邮箱验证YouTube'),
    @('邮' + [char]0xFFFD + ' 验证Netflix', '邮箱验证Netflix'),
    @('邮' + [char]0xFFFD + ' 验证Spotify', '邮箱验证Spotify'),
    @('邮' + [char]0xFFFD + ' 验证AppleMusic', '邮箱验证AppleMusic'),
    @('邮' + [char]0xFFFD + ' 验证AmazonMusic', '邮箱验证AmazonMusic'),
    @('邮' + [char]0xFFFD + ' 验证SoundCloud', '邮箱验证SoundCloud'),
    @('邮' + [char]0xFFFD + ' 验证Tidal', '邮箱验证Tidal'),
    @('邮' + [char]0xFFFD + ' 验证Deezer', '邮箱验证Deezer'),
    @('邮' + [char]0xFFFD + ' 验证Pandora', '邮箱验证Pandora'),
    @('邮' + [char]0xFFFD + ' 验证iHeartRadio', '邮箱验证iHeartRadio'),
    @('邮' + [char]0xFFFD + ' 验证TuneIn', '邮箱验证TuneIn'),
    @('邮' + [char]0xFFFD + ' 验证Audible', '邮箱验证Audible'),
    @('邮' + [char]0xFFFD + ' 验证Kindle', '邮箱验证Kindle'),
    @('邮' + [char]0xFFFD + ' 通知失' + [char]0xFFFD, '邮件通知失败'),
    @('邮' + [char]0xFFFD + ' 通知成功', '邮件通知成功'),
    @('邮' + [char]0xFFFD + ' 通知模' + [char]0xFFFD, '邮件通知模板'),
    @('邮' + [char]0xFFFD + ' 模' + [char]0xFFFD, '邮件模板'),
    @('邮' + [char]0xFFFD + ' 发送', '邮件发送'),
    @('邮' + [char]0xFFFD + ' 订阅', '邮件订阅'),
    @('邮' + [char]0xFFFD + ' 服务', '邮件服务'),
    @('邮' + [char]0xFFFD + ' 设置', '邮件设置'),
    @('邮' + [char]0xFFFD + ' 配' + [char]0xFFFD, '邮件配置'),
    @('邮' + [char]0xFFFD + ' 验证码', '邮件验证码'),
    @('邮' + [char]0xFFFD + ' 验证', '邮件验证'),
    @('邮' + [char]0xFFFD + ' 列表', '邮件列表'),
    @('邮' + [char]0xFFFD + ' 日志', '邮件日志'),
    @('邮' + [char]0xFFFD + ' 草稿', '邮件草稿'),
    @('邮' + [char]0xFFFD + ' 主题', '邮件主题'),
    @('邮' + [char]0xFFFD + ' 内容', '邮件内容'),
    @('邮' + [char]0xFFFD + ' 标题', '邮件标题'),
    @('邮' + [char]0xFFFD + ' 模板', '邮件模板'),
    @('邮' + [char]0xFFFD + ' 发' + [char]0xFFFD + ' 人', '邮件发件人'),
    @('邮' + [char]0xFFFD + ' 收' + [char]0xFFFD + ' 人', '邮件收件人'),
    @('邮' + [char]0xFFFD + ' 回复', '邮件回复'),
    @('邮' + [char]0xFFFD + ' 抄' + [char]0xFFFD, '邮件抄送'),
    @('邮' + [char]0xFFFD + ' 密' + [char]0xFFFD, '邮件密送'),
    @('邮' + [char]0xFFFD + ' 附件', '邮件附件'),
    @('邮' + [char]0xFFFD + ' 类' + [char]0xFFFD, '邮件类型'),
    @('邮' + [char]0xFFFD + ' 状' + [char]0xFFFD, '邮件状态'),
    @('邮' + [char]0xFFFD + ' 优' + [char]0xFFFD + ' 级', '邮件优先级'),
    @('邮' + [char]0xFFFD + ' 失' + [char]0xFFFD, '邮件失败'),
    @('邮' + [char]0xFFFD + ' 成' + [char]0xFFFD, '邮件成功'),
    @('邮' + [char]0xFFFD + ' 无效', '邮件无效'),
    @('邮' + [char]0xFFFD + ' 有效', '邮件有效'),
    @('邮' + [char]0xFFFD + ' 错' + [char]0xFFFD, '邮件错误'),
    @('邮' + [char]0xFFFD + ' 正' + [char]0xFFFD, '邮件正确'),
    @('邮' + [char]0xFFFD + ' 重复', '邮件重复'),
    @('邮' + [char]0xFFFD + ' 唯' + [char]0xFFFD, '邮件唯一'),
    @('邮' + [char]0xFFFD + ' 可' + [char]0xFFFD, '邮件可选'),
    @('邮' + [char]0xFFFD + ' 必填', '邮件必填'),
    @('邮' + [char]0xFFFD + ' 通知', '邮件通知'),
    @('邮' + [char]0xFFFD + ' 推送', '邮件推送'),
    @('验证码模' + [char]0xFFFD, '验证码模块'),
    @('验证码配' + [char]0xFFFD, '验证码配置'),
    @('验证码状' + [char]0xFFFD, '验证码状态'),
    @('验证码图' + [char]0xFFFD, '验证码图片'),
    @('验证码生' + [char]0xFFFD, '验证码生成'),
    @('验证码校' + [char]0xFFFD, '验证码校验'),
    @('验证码验' + [char]0xFFFD, '验证码验证'),
    @('验证码失' + [char]0xFFFD, '验证码失败'),
    @('验证码错' + [char]0xFFFD, '验证码错误'),
    @('验证码已使' + [char]0xFFFD, '验证码已使用'),
    @('验证码已过' + [char]0xFFFD, '验证码已过期'),
    @('验证码无' + [char]0xFFFD, '验证码无效'),
    @('验证码过' + [char]0xFFFD, '验证码过期'),
    @('验证码正' + [char]0xFFFD, '验证码正确'),
    @('验证码不存' + [char]0xFFFD, '验证码不存在'),
    @('验证码数据', '验证码数据'),
    @('验证码类' + [char]0xFFFD, '验证码类型'),
    @('验证码不支' + [char]0xFFFD, '验证码不支持'),
    @('验证码获取', '验证码获取'),
    @('验证码使' + [char]0xFFFD, '验证码使用'),
    @('验证码创' + [char]0xFFFD, '验证码创建'),
    @('邮箱已验' + [char]0xFFFD, '邮箱已验证'),
    @('邮箱未验' + [char]0xFFFD, '邮箱未验证'),
    @('邮箱验' + [char]0xFFFD, '邮箱验证'),
    @('邮箱不存' + [char]0xFFFD, '邮箱不存在'),
    @('邮箱无' + [char]0xFFFD, '邮箱无效'),
    @('邮箱错' + [char]0xFFFD, '邮箱错误'),
    @('邮箱正' + [char]0xFFFD, '邮箱正确'),
    @('邮箱有效', '邮箱有效'),
    @('邮箱' + [char]0xFFFD, '邮箱')
)

foreach ($f in $files) {
    $content = [System.IO.File]::ReadAllText($f.FullName, [System.Text.Encoding]::UTF8)
    $original = $content
    
    foreach ($fix in $fixes) {
        $old = $fix[0]
        $new = $fix[1]
        $content = $content.Replace($old, $new)
    }
    
    # 替换参数调用模式
    $content = $content -replace '&\[\]', 'params![]'
    $content = $content -replace '&params!\[', 'params!['
    
    if ($content -ne $original) {
        [System.IO.File]::WriteAllText($f.FullName, $content, [System.Text.UTF8Encoding]::new($false))
        Write-Host "Fixed: $($f.Name)"
    }
}
Write-Host "Done."
